//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxJarServRef
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RateResponseAttributes", Namespace="http://schemas.datacontract.org/2004/07/Taxjar")]
    public partial class RateResponseAttributes : object
    {
        
        private string CityField;
        
        private decimal CityRateField;
        
        private decimal CombinedDistrictRateField;
        
        private decimal CombinedRateField;
        
        private string CountryField;
        
        private decimal CountryRateField;
        
        private string CountyField;
        
        private decimal CountyRateField;
        
        private decimal DistanceSaleThresholdField;
        
        private bool FreightTaxableField;
        
        private string NameField;
        
        private decimal ParkingRateField;
        
        private decimal ReducedRateField;
        
        private decimal StandardRateField;
        
        private string StateField;
        
        private decimal StateRateField;
        
        private decimal SuperReducedRateField;
        
        private string ZipField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CityRate
        {
            get
            {
                return this.CityRateField;
            }
            set
            {
                this.CityRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CombinedDistrictRate
        {
            get
            {
                return this.CombinedDistrictRateField;
            }
            set
            {
                this.CombinedDistrictRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CombinedRate
        {
            get
            {
                return this.CombinedRateField;
            }
            set
            {
                this.CombinedRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CountryRate
        {
            get
            {
                return this.CountryRateField;
            }
            set
            {
                this.CountryRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County
        {
            get
            {
                return this.CountyField;
            }
            set
            {
                this.CountyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CountyRate
        {
            get
            {
                return this.CountyRateField;
            }
            set
            {
                this.CountyRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DistanceSaleThreshold
        {
            get
            {
                return this.DistanceSaleThresholdField;
            }
            set
            {
                this.DistanceSaleThresholdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FreightTaxable
        {
            get
            {
                return this.FreightTaxableField;
            }
            set
            {
                this.FreightTaxableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ParkingRate
        {
            get
            {
                return this.ParkingRateField;
            }
            set
            {
                this.ParkingRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ReducedRate
        {
            get
            {
                return this.ReducedRateField;
            }
            set
            {
                this.ReducedRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StandardRate
        {
            get
            {
                return this.StandardRateField;
            }
            set
            {
                this.StandardRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StateRate
        {
            get
            {
                return this.StateRateField;
            }
            set
            {
                this.StateRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SuperReducedRate
        {
            get
            {
                return this.SuperReducedRateField;
            }
            set
            {
                this.SuperReducedRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip
        {
            get
            {
                return this.ZipField;
            }
            set
            {
                this.ZipField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/Taxjar")]
    public partial class Order : object
    {
        
        private decimal AmountField;
        
        private string CustomerIdField;
        
        private string ExemptionTypeField;
        
        private string FromCityField;
        
        private string FromCountryField;
        
        private string FromStateField;
        
        private string FromStreetField;
        
        private string FromZipField;
        
        private TaxJarServRef.LineItem[] LineItemsField;
        
        private string ProviderField;
        
        private decimal SalesTaxField;
        
        private decimal ShippingField;
        
        private string ToCityField;
        
        private string ToCountryField;
        
        private string ToStateField;
        
        private string ToStreetField;
        
        private string ToZipField;
        
        private string TransactionDateField;
        
        private string TransactionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExemptionType
        {
            get
            {
                return this.ExemptionTypeField;
            }
            set
            {
                this.ExemptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromCity
        {
            get
            {
                return this.FromCityField;
            }
            set
            {
                this.FromCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromCountry
        {
            get
            {
                return this.FromCountryField;
            }
            set
            {
                this.FromCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromState
        {
            get
            {
                return this.FromStateField;
            }
            set
            {
                this.FromStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromStreet
        {
            get
            {
                return this.FromStreetField;
            }
            set
            {
                this.FromStreetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromZip
        {
            get
            {
                return this.FromZipField;
            }
            set
            {
                this.FromZipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TaxJarServRef.LineItem[] LineItems
        {
            get
            {
                return this.LineItemsField;
            }
            set
            {
                this.LineItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provider
        {
            get
            {
                return this.ProviderField;
            }
            set
            {
                this.ProviderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SalesTax
        {
            get
            {
                return this.SalesTaxField;
            }
            set
            {
                this.SalesTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Shipping
        {
            get
            {
                return this.ShippingField;
            }
            set
            {
                this.ShippingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToCity
        {
            get
            {
                return this.ToCityField;
            }
            set
            {
                this.ToCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToCountry
        {
            get
            {
                return this.ToCountryField;
            }
            set
            {
                this.ToCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToState
        {
            get
            {
                return this.ToStateField;
            }
            set
            {
                this.ToStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToStreet
        {
            get
            {
                return this.ToStreetField;
            }
            set
            {
                this.ToStreetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToZip
        {
            get
            {
                return this.ToZipField;
            }
            set
            {
                this.ToZipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionDate
        {
            get
            {
                return this.TransactionDateField;
            }
            set
            {
                this.TransactionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LineItem", Namespace="http://schemas.datacontract.org/2004/07/Taxjar")]
    public partial class LineItem : object
    {
        
        private string DescriptionField;
        
        private decimal DiscountField;
        
        private string IdField;
        
        private string ProductIdentifierField;
        
        private string ProductTaxCodeField;
        
        private int QuantityField;
        
        private decimal SalesTaxField;
        
        private decimal UnitPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Discount
        {
            get
            {
                return this.DiscountField;
            }
            set
            {
                this.DiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductIdentifier
        {
            get
            {
                return this.ProductIdentifierField;
            }
            set
            {
                this.ProductIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductTaxCode
        {
            get
            {
                return this.ProductTaxCodeField;
            }
            set
            {
                this.ProductTaxCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SalesTax
        {
            get
            {
                return this.SalesTaxField;
            }
            set
            {
                this.SalesTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice
        {
            get
            {
                return this.UnitPriceField;
            }
            set
            {
                this.UnitPriceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxResponseAttributes", Namespace="http://schemas.datacontract.org/2004/07/Taxjar")]
    public partial class TaxResponseAttributes : object
    {
        
        private decimal AmountToCollectField;
        
        private TaxJarServRef.TaxBreakdown BreakdownField;
        
        private string ExemptionTypeField;
        
        private bool FreightTaxableField;
        
        private bool HasNexusField;
        
        private TaxJarServRef.TaxJurisdictions JurisdictionsField;
        
        private decimal OrderTotalAmountField;
        
        private decimal RateField;
        
        private decimal ShippingField;
        
        private string TaxSourceField;
        
        private decimal TaxableAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AmountToCollect
        {
            get
            {
                return this.AmountToCollectField;
            }
            set
            {
                this.AmountToCollectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TaxJarServRef.TaxBreakdown Breakdown
        {
            get
            {
                return this.BreakdownField;
            }
            set
            {
                this.BreakdownField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExemptionType
        {
            get
            {
                return this.ExemptionTypeField;
            }
            set
            {
                this.ExemptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FreightTaxable
        {
            get
            {
                return this.FreightTaxableField;
            }
            set
            {
                this.FreightTaxableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasNexus
        {
            get
            {
                return this.HasNexusField;
            }
            set
            {
                this.HasNexusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TaxJarServRef.TaxJurisdictions Jurisdictions
        {
            get
            {
                return this.JurisdictionsField;
            }
            set
            {
                this.JurisdictionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderTotalAmount
        {
            get
            {
                return this.OrderTotalAmountField;
            }
            set
            {
                this.OrderTotalAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rate
        {
            get
            {
                return this.RateField;
            }
            set
            {
                this.RateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Shipping
        {
            get
            {
                return this.ShippingField;
            }
            set
            {
                this.ShippingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxSource
        {
            get
            {
                return this.TaxSourceField;
            }
            set
            {
                this.TaxSourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TaxableAmount
        {
            get
            {
                return this.TaxableAmountField;
            }
            set
            {
                this.TaxableAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxBreakdown", Namespace="http://schemas.datacontract.org/2004/07/Taxjar")]
    public partial class TaxBreakdown : TaxJarServRef.Breakdown
    {
        
        private decimal CityTaxCollectableField;
        
        private decimal CountyTaxCollectableField;
        
        private TaxJarServRef.TaxBreakdownLineItem[] LineItemsField;
        
        private TaxJarServRef.TaxBreakdownShipping ShippingField;
        
        private decimal SpecialDistrictTaxCollectableField;
        
        private decimal SpecialDistrictTaxRateField;
        
        private decimal SpecialDistrictTaxableAmountField;
        
        private decimal StateTaxCollectableField;
        
        private decimal StateTaxRateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CityTaxCollectable
        {
            get
            {
                return this.CityTaxCollectableField;
            }
            set
            {
                this.CityTaxCollectableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CountyTaxCollectable
        {
            get
            {
                return this.CountyTaxCollectableField;
            }
            set
            {
                this.CountyTaxCollectableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TaxJarServRef.TaxBreakdownLineItem[] LineItems
        {
            get
            {
                return this.LineItemsField;
            }
            set
            {
                this.LineItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TaxJarServRef.TaxBreakdownShipping Shipping
        {
            get
            {
                return this.ShippingField;
            }
            set
            {
                this.ShippingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SpecialDistrictTaxCollectable
        {
            get
            {
                return this.SpecialDistrictTaxCollectableField;
            }
            set
            {
                this.SpecialDistrictTaxCollectableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SpecialDistrictTaxRate
        {
            get
            {
                return this.SpecialDistrictTaxRateField;
            }
            set
            {
                this.SpecialDistrictTaxRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SpecialDistrictTaxableAmount
        {
            get
            {
                return this.SpecialDistrictTaxableAmountField;
            }
            set
            {
                this.SpecialDistrictTaxableAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StateTaxCollectable
        {
            get
            {
                return this.StateTaxCollectableField;
            }
            set
            {
                this.StateTaxCollectableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StateTaxRate
        {
            get
            {
                return this.StateTaxRateField;
            }
            set
            {
                this.StateTaxRateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxJurisdictions", Namespace="http://schemas.datacontract.org/2004/07/Taxjar")]
    public partial class TaxJurisdictions : object
    {
        
        private string CityField;
        
        private string CountryField;
        
        private string CountyField;
        
        private string StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County
        {
            get
            {
                return this.CountyField;
            }
            set
            {
                this.CountyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Breakdown", Namespace="http://schemas.datacontract.org/2004/07/Taxjar")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TaxJarServRef.TaxBreakdownLineItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TaxJarServRef.TaxBreakdownShipping))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TaxJarServRef.TaxBreakdown))]
    public partial class Breakdown : object
    {
        
        private decimal CityTaxRateField;
        
        private decimal CityTaxableAmountField;
        
        private decimal CombinedTaxRateField;
        
        private decimal CountryTaxCollectableField;
        
        private decimal CountryTaxRateField;
        
        private decimal CountryTaxableAmountField;
        
        private decimal CountyTaxRateField;
        
        private decimal CountyTaxableAmountField;
        
        private decimal GSTField;
        
        private decimal GSTTaxRateField;
        
        private decimal GSTTaxableAmountField;
        
        private decimal PSTField;
        
        private decimal PSTTaxRateField;
        
        private decimal PSTTaxableAmountField;
        
        private decimal QSTField;
        
        private decimal QSTTaxRateField;
        
        private decimal QSTTaxableAmountField;
        
        private decimal StateTaxableAmountField;
        
        private decimal TaxCollectableField;
        
        private decimal TaxableAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CityTaxRate
        {
            get
            {
                return this.CityTaxRateField;
            }
            set
            {
                this.CityTaxRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CityTaxableAmount
        {
            get
            {
                return this.CityTaxableAmountField;
            }
            set
            {
                this.CityTaxableAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CombinedTaxRate
        {
            get
            {
                return this.CombinedTaxRateField;
            }
            set
            {
                this.CombinedTaxRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CountryTaxCollectable
        {
            get
            {
                return this.CountryTaxCollectableField;
            }
            set
            {
                this.CountryTaxCollectableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CountryTaxRate
        {
            get
            {
                return this.CountryTaxRateField;
            }
            set
            {
                this.CountryTaxRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CountryTaxableAmount
        {
            get
            {
                return this.CountryTaxableAmountField;
            }
            set
            {
                this.CountryTaxableAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CountyTaxRate
        {
            get
            {
                return this.CountyTaxRateField;
            }
            set
            {
                this.CountyTaxRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CountyTaxableAmount
        {
            get
            {
                return this.CountyTaxableAmountField;
            }
            set
            {
                this.CountyTaxableAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GST
        {
            get
            {
                return this.GSTField;
            }
            set
            {
                this.GSTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GSTTaxRate
        {
            get
            {
                return this.GSTTaxRateField;
            }
            set
            {
                this.GSTTaxRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GSTTaxableAmount
        {
            get
            {
                return this.GSTTaxableAmountField;
            }
            set
            {
                this.GSTTaxableAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PST
        {
            get
            {
                return this.PSTField;
            }
            set
            {
                this.PSTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PSTTaxRate
        {
            get
            {
                return this.PSTTaxRateField;
            }
            set
            {
                this.PSTTaxRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PSTTaxableAmount
        {
            get
            {
                return this.PSTTaxableAmountField;
            }
            set
            {
                this.PSTTaxableAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal QST
        {
            get
            {
                return this.QSTField;
            }
            set
            {
                this.QSTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal QSTTaxRate
        {
            get
            {
                return this.QSTTaxRateField;
            }
            set
            {
                this.QSTTaxRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal QSTTaxableAmount
        {
            get
            {
                return this.QSTTaxableAmountField;
            }
            set
            {
                this.QSTTaxableAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StateTaxableAmount
        {
            get
            {
                return this.StateTaxableAmountField;
            }
            set
            {
                this.StateTaxableAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TaxCollectable
        {
            get
            {
                return this.TaxCollectableField;
            }
            set
            {
                this.TaxCollectableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TaxableAmount
        {
            get
            {
                return this.TaxableAmountField;
            }
            set
            {
                this.TaxableAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxBreakdownLineItem", Namespace="http://schemas.datacontract.org/2004/07/Taxjar")]
    public partial class TaxBreakdownLineItem : TaxJarServRef.Breakdown
    {
        
        private decimal CityAmountField;
        
        private decimal CountyAmountField;
        
        private string IdField;
        
        private decimal SpecialDistrictAmountField;
        
        private decimal SpecialDistrictTaxableAmountField;
        
        private decimal SpecialTaxRateField;
        
        private decimal StateAmountField;
        
        private decimal StateSalesTaxRateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CityAmount
        {
            get
            {
                return this.CityAmountField;
            }
            set
            {
                this.CityAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CountyAmount
        {
            get
            {
                return this.CountyAmountField;
            }
            set
            {
                this.CountyAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SpecialDistrictAmount
        {
            get
            {
                return this.SpecialDistrictAmountField;
            }
            set
            {
                this.SpecialDistrictAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SpecialDistrictTaxableAmount
        {
            get
            {
                return this.SpecialDistrictTaxableAmountField;
            }
            set
            {
                this.SpecialDistrictTaxableAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SpecialTaxRate
        {
            get
            {
                return this.SpecialTaxRateField;
            }
            set
            {
                this.SpecialTaxRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StateAmount
        {
            get
            {
                return this.StateAmountField;
            }
            set
            {
                this.StateAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StateSalesTaxRate
        {
            get
            {
                return this.StateSalesTaxRateField;
            }
            set
            {
                this.StateSalesTaxRateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxBreakdownShipping", Namespace="http://schemas.datacontract.org/2004/07/Taxjar")]
    public partial class TaxBreakdownShipping : TaxJarServRef.Breakdown
    {
        
        private decimal CityAmountField;
        
        private decimal CountyAmountField;
        
        private decimal SpecialDistrictAmountField;
        
        private decimal SpecialDistrictTaxRateField;
        
        private decimal SpecialDistrictTaxableAmountField;
        
        private decimal StateAmountField;
        
        private decimal StateSalesTaxRateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CityAmount
        {
            get
            {
                return this.CityAmountField;
            }
            set
            {
                this.CityAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CountyAmount
        {
            get
            {
                return this.CountyAmountField;
            }
            set
            {
                this.CountyAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SpecialDistrictAmount
        {
            get
            {
                return this.SpecialDistrictAmountField;
            }
            set
            {
                this.SpecialDistrictAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SpecialDistrictTaxRate
        {
            get
            {
                return this.SpecialDistrictTaxRateField;
            }
            set
            {
                this.SpecialDistrictTaxRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SpecialDistrictTaxableAmount
        {
            get
            {
                return this.SpecialDistrictTaxableAmountField;
            }
            set
            {
                this.SpecialDistrictTaxableAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StateAmount
        {
            get
            {
                return this.StateAmountField;
            }
            set
            {
                this.StateAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StateSalesTaxRate
        {
            get
            {
                return this.StateSalesTaxRateField;
            }
            set
            {
                this.StateSalesTaxRateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaxJarServRef.ITaxCalculator")]
    public interface ITaxCalculator
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxCalculator/GetRateFromZip", ReplyAction="http://tempuri.org/ITaxCalculator/GetRateFromZipResponse")]
        System.Threading.Tasks.Task<TaxJarServRef.RateResponseAttributes> GetRateFromZipAsync(string usZipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxCalculator/GetTaxForOrder", ReplyAction="http://tempuri.org/ITaxCalculator/GetTaxForOrderResponse")]
        System.Threading.Tasks.Task<TaxJarServRef.TaxResponseAttributes> GetTaxForOrderAsync(TaxJarServRef.Order ord);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ITaxCalculatorChannel : TaxJarServRef.ITaxCalculator, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class TaxCalculatorClient : System.ServiceModel.ClientBase<TaxJarServRef.ITaxCalculator>, TaxJarServRef.ITaxCalculator
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TaxCalculatorClient() : 
                base(TaxCalculatorClient.GetDefaultBinding(), TaxCalculatorClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITaxCalculator.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaxCalculatorClient(EndpointConfiguration endpointConfiguration) : 
                base(TaxCalculatorClient.GetBindingForEndpoint(endpointConfiguration), TaxCalculatorClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaxCalculatorClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TaxCalculatorClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaxCalculatorClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TaxCalculatorClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaxCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<TaxJarServRef.RateResponseAttributes> GetRateFromZipAsync(string usZipCode)
        {
            return base.Channel.GetRateFromZipAsync(usZipCode);
        }
        
        public System.Threading.Tasks.Task<TaxJarServRef.TaxResponseAttributes> GetTaxForOrderAsync(TaxJarServRef.Order ord)
        {
            return base.Channel.GetTaxForOrderAsync(ord);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITaxCalculator))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITaxCalculator))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50728/TaxCalculator.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TaxCalculatorClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITaxCalculator);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TaxCalculatorClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITaxCalculator);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ITaxCalculator,
        }
    }
}
